### ISSUE TITLE
How can I make a "result image" from trained model ?

### ISSUE THREAD

**Issue by bemoregt** [IanTaehoonYoo/semantic-segmentation-pytorch#1]
Hi, @IanTaehoonYoo 

How can I make a "result image" from trained model ?
I can't found that code...

Thanks in advance.

Best,
@bemoregt.

**Comment by IanTaehoonYoo** [comment]
Hi, @bemoregt 

You can find the code in the Trainer class, and the line is 160.
Also, the result images will be saved in the runs folder if you run this project.

If you have any questions, please let me know.

Thank you,
Best Regards,

@IanTaehoonYoo
