### ISSUE TITLE
sir,I find it(fcn8-vgg16) accuracy only 0.2657, how the result  so terrible ?

### ISSUE THREAD

**Issue by LeeNannaner** [IanTaehoonYoo/semantic-segmentation-pytorch#12]
![image](https://user-images.githubusercontent.com/57003018/97310347-1324a480-189e-11eb-85b3-8a2640d32b4c.png)

**Comment by LeeNannaner** [comment]
![image](https://user-images.githubusercontent.com/57003018/97385948-c8db0c00-190d-11eb-9d30-4531bb6fef5b.png)
And the test result is lower greatly than the train.

**Comment by LeeNannaner** [comment]
Dear sir, could you give me some suggestions?

**Comment by IanTaehoonYoo** [comment]
Hi LeeNananer,

I guess you trained the sample dataset in this project, and it is too little data to train. It is called 'overfitting', so you should download the Cityspace dataset.
Also, I suggest the image size should be greater than 500x500 if you train PSPnet.

**Comment by LeeNannaner** [comment]
Oh，oh，thanks sir. I will have a try.




            
            
                
                    
                            
                                
                            
                            
                                linannan2019
                            
                            
                                
                            
                    
                        
                            
                                    邮箱：linannan2019@sjtu.edu.cn
                            
                        
                
            
        Signature is customized by Netease Mail Master


On 10/29/2020 11:48, IanYoo wrote: 
Hi LeeNananer,
I guess you trained the sample dataset in this project, and it is too little data to train. It is called 'overfitting', so you should download Cityspace dataset.
Also, I suggest the image size should be greater than 500x500 if you train PSPnet.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/IanTaehoonYoo/semantic-segmentation-pytorch/issues/12#issuecomment-718341630",
"url": "https://github.com/IanTaehoonYoo/semantic-segmentation-pytorch/issues/12#issuecomment-718341630",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by LeeNannaner** [comment]
Oh，oh，thanks sir. I will have a try.

**Comment by zhou-rui1** [comment]
Hi, how can it train with the image size greater than 500x500 ? 

once I try to train with greater size (batchsize=2), it give this, :
`CUDA out of memory. Tried to allocate 18.00 MiB (GPU 0; 15.90 GiB total capacity; 15.02 GiB already allocated; 17.75 MiB free; 15.08 GiB reserved in total by PyTorch)`

Appreciate for any guidance!
