### ISSUE TITLE
Dear sir, I find one thing interesting,when I use finetune(pretrained =true; fixedfeature=ture), the result is worse than (pretrained =true; fixedfeature=false) 

### ISSUE THREAD

**Issue by LeeNannaner** [IanTaehoonYoo/semantic-segmentation-pytorch#13]
![image](https://user-images.githubusercontent.com/57003018/97953368-35a54900-1ddb-11eb-942a-192784b3b58c.png)

**Comment by LeeNannaner** [comment]
Do you know the reason?

**Comment by IanTaehoonYoo** [comment]
Hi LeeNannaner,

'fixedfeature=true' means that the pre-trained model is fixed and the pre-trained weights can not be changed. 
I hope [this article](https://stats.stackexchange.com/questions/331369/what-is-meant-by-fine-tuning-of-neural-network) can help you.

**Comment by LeeNannaner** [comment]
Thanks sir, so nice of you !
