### ISSUE TITLE
 what is train_epoch_batch_.png represents?

### ISSUE THREAD

**Issue by zhou-rui1** [IanTaehoonYoo/semantic-segmentation-pytorch#14]
the file in the training process such as : train_epoch_8_batch_0.png contains three lines,the third one is the input image, then which is the difference between the first and the second line?
can you explain it a little for me, I am confusing and cannot find any reference....

**Comment by IanTaehoonYoo** [comment]
Hi zhou-rui1,

"epoch_8" means that the train's epoch is 9th. "batch_0" is the first batch.
It's a count training the model.

**Comment by zhou-rui1** [comment]
Thanks a lot. 
But what I mean is the .png for the training process, it presents three lines of images each epoch( batch=8, 8 images each line),what's the difference between the first and second lines images? such as this one:
https://drive.google.com/file/d/107de7m3rBEmhB0ThX4lNuguW6IpwnCwK/view?usp=sharing

**Comment by IanTaehoonYoo** [comment]
Oh, I could understand when I saw your image.
The first line images are predicted images and output images.
The second line images are ground truth images and labeled images.
