### ISSUE TITLE
: Given transposed=1, weight of size 1024 2048 4 4, expected input[8, 2048, 10, 10] to have 1024 channels, but got 2048 channels instead

### ISSUE THREAD

**Issue by jiafengshen** [IanTaehoonYoo/semantic-segmentation-pytorch#3]

**Comment by IanTaehoonYoo** [comment]
Hi, @jiafengshen 
Could you give me some information you used the model and input data?

Thanks
Best regards,

**Comment by IanTaehoonYoo** [comment]
I found that problem when testing the model 'unet_resnet34' and I fixed it.
I update the project, so you should update it. use the command: pip install --upgrade seg-torch

Thanks
